version: '3.6'

services:
  face-detect-api:
    container_name: backend
    # image: node:8.11.1
    build: ./
    command: npm start
    working_dir: /usr/src/face-detect-api
    ports:
      - "3000:3000"